### ISSUE TITLE
Sorry, we could not find any repositories to migrate

### ISSUE THREAD

**Issue by balupton** [travis-ci/travis_migrate_to_apps#4]
I have hundreds of repositories using the .org, however when I run the script I get:

```
> travis_migrate_to_apps bevry X X
Starting to migrate the account bevry to use the Travis CI GitHub App integration.
Looking up bevry's GitHub App installation.
Looking up bevry's active repositories.
Sorry, we could not find any repositories to migrate
```

Despite when I go to https://travis-ci.com/bevry/badges I am greeted with:

<img width="1079" alt="screen shot 2018-11-23 at 12 37 28 pm" src="https://user-images.githubusercontent.com/61148/48925852-8d16bb00-ef1c-11e8-9385-0d7e9d99120f.png">

Could I please have all repos on `balupton`, `bevry`, `docpad`, `browserstate`, `bevry-trading`, `chainyjs`, `interconnectapp`, `webwrite` moved over

**Comment by cotsog** [comment]
@balupton Sorry for the confusion. This script is to migrate **private repos** from travis-ci.com from legacy GitHub Services integration to the new GitHub Apps integration (on travis-ci.com too).

To migrate your **open source repository** from travis-ci.org to travis-ci.com, could you send us an e-mail at support [at] travis-ci [dot] com? In your email, please include:

* “Repository Migration” somewhere in the subject line, and
* the repository’s name in your email

Thanks in advance and we will continue from there.
